### ISSUE TITLE
Doesn't work with the latest version of stardog

### ISSUE THREAD

**Issue by murphp15** [WDAqua/Qanary#17]
I can't run this with the latest version of stardog and I can't find the older versions online to download.

**Comment by anbo-de** [comment]
Please check the latest version of [Qanary pipeline](https://github.com/WDAqua/Qanary/tree/master/qanary_pipeline-template) (v1.1.1+) where I implemented a patch for Stardog v5+ (see https://community.stardog.com/t/query-and-update-endpoint-stardog-5/530/2 for the root cause). Please add here a commit if you find any more problems or not.

**Comment by anbo-de** [comment]
Forgot to close the ticket as it was solved in #14.
