### ISSUE TITLE
Pipeline component wrong prefix

### ISSUE THREAD

**Issue by D063520** [WDAqua/Qanary#8]
Use qa instead of qa in QuestionAnsweringController when creating the starting objects.

**Comment by anbo-de** [comment]
Please add some details and clarify the problem.

**Comment by kulsingh** [comment]
In the file QanaryQuestionAnsweringController.java at  https://github.com/WDAqua/Qanary/blob/master/qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java#L215, the prefix used in anno1 and anno2 is oa, instead of qa. While integrating the new wrapper, we found that it is a bug. Hence, while adding the new annotation (lets say anno3 in our case for new language) and creating a new starting object, qa needs to be used instead of oa, otherwise error will appear.

**Comment by anbo-de** [comment]
I think that task was done a long time ago.
